name: interact.js
description : interact.js - Powerful, flexible, snappable drag and drop, resizing and multi-touch gestures for modern browsers
baseurl     : ""
url         : http://interactjs.io
pygments    : true
timezone    : Europe/Dublin

markdown    : redcarpet
redcarpet:
      extensions: [tables, laxed_spacing, fenced_code_blocks, strikethrough, autolink, superscript, no_intra_emphasis, with_toc_data]
